baseURL = 'https://gokhan.tr/'
languageCode = 'en-US'
title = 'Gokhan Ozturk'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[build]
  [[build.cachebusters]]
    source = 'layouts/.*'
    target = 'css'
