name = 'Portfolio'
license = 'MIT'
licenselink = 'https://github.com/goztrk/goztrk.github.io/LICENSE'
description = 'Theme description'

# The home page of the theme, where the source can be found
homepage = 'https://gokhan.tr'

# If you have a running demo of the theme
demosite = 'https://gokhan.tr'

# Taxonomy terms
tags = ['blog', 'company']
features = ['some', 'awesome', 'features']

# If the theme has a single author
[author]
  name = 'Gokhan Ozturk'
  homepage = 'https://gokhan.tr'

